#!/bin/bash

# TODO: generate this file... termite should handle it!
if ! [ -d node_modules/ ]; then
	npm i
fi

SCRIPT=${1:-/usr/local/bin}/tinify
cat > $SCRIPT <<EOM
#!/bin/bash

$(pwd)/tinify.js \$@

EOM
chmod +x $SCRIPT
# And that should do it!
echo "INSTALLED @ $SCRIPT"
